<a href="https://colab.research.google.com/github/Naveen-gale/nlp_lerning/blob/main/lang_detection(nlp).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Language Detection.csv")

In [3]:
df.head()

                                                Text Language
0   Nature, in the broadest sense, is the natural...  English
1  "Nature" can refer to the phenomena of the phy...  English
2  The study of nature is a large, if not the onl...  English
3  Although humans are part of nature, human acti...  English
4  [1] The word nature is borrowed from the Old F...  English

In [4]:
df.isnull().sum()

Text        0
Language    0
dtype: int64

In [5]:
df['Language'].value_counts()

Language
English       1385
French        1014
Spanish        819
Portugeese     739
Italian        698
Russian        692
Sweedish       676
Malayalam      594
Dutch          546
Arabic         536
Turkish        474
German         470
Tamil          469
Danish         428
Kannada        369
Greek          365
Hindi           63
Name: count, dtype: int64

In [6]:
df['text']= df['Text'].str.strip()

In [7]:
import re

df["text"] = df["text"].apply(lambda x: re.sub(r"\s+", " ", x))

In [8]:
df = df[df["text"] != ""]

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5)
)
X= vectorizer.fit_transform(df["text"])

In [21]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(df["Language"])
#

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(
 X, y, test_size=0.33, random_state=42)

In [24]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(multi_class="multinomial", solver="lbfgs")
model.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

LogisticRegression(multi_class='multinomial')

In [25]:
pred = model.predict(X_test)

In [26]:
from sklearn.metrics import accuracy_score
acc= accuracy_score(y_test, pred)

In [27]:
from sklearn.metrics import classification_report
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00       182
           1       0.99      0.93      0.96       139
           2       1.00      0.96      0.98       187
           3       0.96      1.00      0.98       486
           4       0.98      0.99      0.98       340
           5       0.98      0.98      0.98       147
           6       1.00      0.99      1.00       112
           7       1.00      0.85      0.92        20
           8       0.99      0.98      0.99       237
           9       1.00      1.00      1.00       109
          10       1.00      0.99      0.99       200
          11       0.98      0.95      0.97       241
          12       0.97      1.00      0.98       217
          13       0.97      0.98      0.98       269
          14       0.96      0.98      0.97       215
          15       1.00      0.99      1.00       155
          16       1.00      0.99      1.00       156

    accuracy                           0.98      3412
   macro avg       0.99      0.97      0.98      3412
weighted avg       0.98      0.98      0.98      3412

In [17]:
import joblib
model = joblib.dump(model, "model.pkl")

In [19]:
print(dict(zip(le.transform(le.classes_), le.classes_)))

{np.int64(0): 'Arabic', np.int64(1): 'Danish', np.int64(2): 'Dutch', np.int64(3): 'English', np.int64(4): 'French', np.int64(5): 'German', np.int64(6): 'Greek', np.int64(7): 'Hindi', np.int64(8): 'Italian', np.int64(9): 'Kannada', np.int64(10): 'Malayalam', np.int64(11): 'Portugeese', np.int64(12): 'Russian', np.int64(13): 'Spanish', np.int64(14): 'Sweedish', np.int64(15): 'Tamil', np.int64(16): 'Turkish'}

In [28]:
from sklearn.svm import LinearSVC
svm = LinearSVC()
svm.fit(X_train, y_train)

LinearSVC()

In [29]:
svm_pred = svm.predict(X_test)

In [30]:
svm_acc = accuracy_score(y_test, svm_pred)

In [31]:
svm_acc

0.9856389214536928

In [33]:
print(classification_report(y_test, svm_pred))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00       182
           1       0.95      0.96      0.96       139
           2       1.00      0.98      0.99       187
           3       0.98      1.00      0.99       486
           4       0.99      0.99      0.99       340
           5       0.98      0.98      0.98       147
           6       1.00      0.99      1.00       112
           7       1.00      1.00      1.00        20
           8       0.98      0.98      0.98       237
           9       1.00      1.00      1.00       109
          10       1.00      0.99      1.00       200
          11       0.98      0.96      0.97       241
          12       0.99      1.00      1.00       217
          13       0.97      0.97      0.97       269
          14       0.98      0.97      0.97       215
          15       1.00      1.00      1.00       155
          16       0.99      0.99      0.99       156

    accuracy                           0.99      3412
   macro avg       0.99      0.99      0.99      3412
weighted avg       0.99      0.99      0.99      3412

In [34]:
df.head()

,Text,Language,text
0,"Nature, in the broadest sense, is the natural...",English,"Nature, in the broadest sense, is the natural,..."
1,"""Nature"" can refer to the phenomena of the phy...",English,"""Nature"" can refer to the phenomena of the phy..."
2,"The study of nature is a large, if not the onl...",English,"The study of nature is a large, if not the onl..."
3,"Although humans are part of nature, human acti...",English,"Although humans are part of nature, human acti..."
4,[1] The word nature is borrowed from the Old F...,English,[1] The word nature is borrowed from the Old F...

In [36]:
train_acc = svm.score(X_train, y_train)
test_acc = svm.score(X_test, y_test)

print("Train Accuracy:", train_acc)
print("Test Accuracy :", test_acc)

Train Accuracy: 0.99971119133574
Test Accuracy : 0.9856389214536928

In [37]:
import joblib
joblib.dump(svm, "svm_model.pkl")

['svm_model.pkl']